name: Generate Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rhrebecek
          template: classic
          filename: github-metrics.svg
          base: activity, community, repositories, metadata
          config_timezone: Europe/Prague
          base_hireable: yes
          plugin_introduction: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.kurzy.cz/zpravy/util/forext.dat?type=rss
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: codexcz
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: rhrebecek
