name: Generate Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Prague
          template: classic
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata

          # 🔹 Calendar commits
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # 🔹 Contributors
          plugin_contributors: yes
          plugin_contributors_contributions: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
